spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 789742733227-cm44o0vdkqn734ng26rqb0bg4qbivq5n.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8080
